name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-devdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build docs
        run: |
          npm install
          npm run docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs # The branch the action should deploy to.
          folder: devdocs # The folder the action should deploy.