name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build:forTests
          npm run docs
          version=$(node -p "require('./package.json').version")
          cp -r dist demos/dist
          cp -r devdocs demos/
          mkdir -p demos/$version
          cp -r devdocs/* demos/devdocs/$version

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo # The branch the action should deploy to.
          folder: demos # The folder the action should deploy.
