name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build:github
          npm run build:docs
          version=$(node -p "require('./packages/niivue/package.json').version")
          cp -r packages/niivue/dist packages/niivue/demos/dist
          cp -r packages/niivue/devdocs packages/niivue/demos/
          mkdir -p packages/niivue/demos/devdocs/$version
          cp -r packages/niivue/devdocs/* packages/niivue/demos/devdocs/$version

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo # The branch the action should deploy to.
          folder: packages/niivue/demos # The folder the action should deploy.
